# Generated by Django 2.1.5 on 2019-01-31 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190131_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='teams',
            field=models.ManyToManyField(blank=True, help_text='Specific Departments for this user.', related_name='user_set', related_query_name='user', to='users.Team', verbose_name='サークル'),
        ),
    ]
