# Generated by Django 2.1.5 on 2019-01-31 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190131_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='コース')),
            ],
            options={
                'verbose_name': 'コース',
                'verbose_name_plural': 'コース',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='course',
            field=models.ForeignKey(blank=True, default=1, help_text='Specific course for this user.', on_delete=django.db.models.deletion.PROTECT, related_name='user_set', related_query_name='user', to='users.Course', verbose_name='コース'),
        ),
    ]
