# Generated by Django 2.1.5 on 2019-02-01 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190201_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='departments',
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Specific Departments for this user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.Department', verbose_name='学部'),
        ),
        migrations.AddField(
            model_name='user',
            name='university',
            field=models.ForeignKey(blank=True, help_text='Specific University for this user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.University', verbose_name='大学'),
        ),
        migrations.AlterField(
            model_name='user',
            name='teams',
            field=models.ManyToManyField(blank=True, help_text='Specific サークル for this user.', related_name='users', to='users.Team', verbose_name='サークル'),
        ),
    ]
