# Generated by Django 2.1.5 on 2019-02-01 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190201_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='university',
            field=models.ForeignKey(blank=True, help_text='Specific University for this user.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='users.University', verbose_name='大学'),
        ),
    ]
