# Generated by Django 2.1.5 on 2019-02-01 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_department_university'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'コース・学科', 'verbose_name_plural': 'コース・学科'},
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Specific Department for this user.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='users.Department', verbose_name='学部'),
        ),
        migrations.AddField(
            model_name='team',
            name='university',
            field=models.ForeignKey(blank=True, help_text='Specific University for this user.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='users.University', verbose_name='大学'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(blank=True, max_length=150, verbose_name='コース・学科'),
        ),
    ]
