# Generated by Django 2.1.5 on 2019-02-01 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190201_2354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'ユーザー', 'verbose_name_plural': 'ユーザー'},
        ),
        migrations.AddField(
            model_name='course',
            name='university',
            field=models.ForeignKey(blank=True, help_text='Specific University for this user.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='users.University', verbose_name='大学'),
        ),
        migrations.AddField(
            model_name='team',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Specific Department for this user.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='users.Department', verbose_name='学部'),
        ),
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Specific Department for this user.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='users.Department', verbose_name='学部'),
        ),
    ]
