# Generated by Django 2.1.5 on 2019-02-02 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20190202_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='header',
            field=models.URLField(blank=True, verbose_name='header'),
        ),
        migrations.AddField(
            model_name='team',
            name='is_official',
            field=models.BooleanField(default=False, help_text='公認サークルかどうか', verbose_name='official status'),
        ),
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.URLField(blank=True, verbose_name='logo'),
        ),
        migrations.AddField(
            model_name='team',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='url',
            field=models.URLField(blank=True, verbose_name='url'),
        ),
    ]
