# Generated by Django 2.1.5 on 2019-02-02 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20190202_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='content',
            field=models.TextField(blank=True, verbose_name='Team content'),
        ),
        migrations.AlterField(
            model_name='team',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ownteams', to=settings.AUTH_USER_MODEL, verbose_name='代表者'),
        ),
    ]
