# Generated by Django 2.1.5 on 2019-02-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gql', '0016_auto_20190204_1743'),
        ('users', '0015_auto_20190203_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='projects',
            field=models.ManyToManyField(blank=True, help_text='Specific Project for this user.', related_name='users', to='gql.Project', verbose_name='キャンプ'),
        ),
    ]
