# Generated by Django 2.1.7 on 2019-03-08 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gql', '0023_project_category'),
        ('users', '0017_auto_20190214_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liked', to='gql.Project', verbose_name='キャンプ')),
            ],
            options={
                'verbose_name': 'Like',
                'verbose_name_plural': 'Like',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='testimg',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Specific course for this user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.Course', verbose_name='コース・学科'),
        ),
        migrations.AddField(
            model_name='likeproject',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liked', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
    ]
