# Generated by Django 2.1.7 on 2019-03-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_user_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='testimg',
        ),
        migrations.AddField(
            model_name='user',
            name='logo',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='logo'),
        ),
    ]
