# Generated by Django 2.1.7 on 2019-03-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20190324_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='testimg',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='testimg'),
        ),
    ]
