# Generated by Django 2.1.7 on 2019-03-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_user_testimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='logo',
            field=models.ImageField(blank=True, upload_to='logo/', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='testimg',
            field=models.ImageField(blank=True, upload_to='testimgs/', verbose_name='testimg'),
        ),
    ]
