# Generated by Django 2.1.7 on 2019-03-29 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20190329_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='displayname',
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, max_length=150, verbose_name='position'),
        ),
    ]
