# Generated by Django 2.1.7 on 2019-03-29 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gql', '0032_auto_20190329_1527'),
        ('users', '0025_auto_20190329_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liked', to='gql.Project', verbose_name='キャンプ')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liked', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'Like',
                'verbose_name_plural': 'Like',
            },
        ),
        migrations.RemoveField(
            model_name='likeproject',
            name='project',
        ),
        migrations.RemoveField(
            model_name='likeproject',
            name='user',
        ),
        migrations.DeleteModel(
            name='LikeProject',
        ),
    ]
