# Generated by Django 2.1.7 on 2019-03-30 07:09

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20190330_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='header',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=0, size=[1920, 1080], upload_to='header/', verbose_name='header'),
        ),
        migrations.AlterField(
            model_name='user',
            name='logo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=0, size=[400, 400], upload_to='logo/', verbose_name='logo'),
        ),
    ]
