# Generated by Django 2.1.7 on 2019-03-30 07:35

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20190330_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='logo',
        ),
        migrations.AddField(
            model_name='team',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=0, size=[600, 300], upload_to='thumbnail/', verbose_name='ヘッダーthumbnail'),
        ),
        migrations.AddField(
            model_name='user',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=0, size=[600, 300], upload_to='thumbnail/', verbose_name='ヘッダーthumbnail'),
        ),
        migrations.AlterField(
            model_name='team',
            name='header',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=0, size=[1920, 1080], upload_to='header/', verbose_name='header'),
        ),
    ]
