# Generated by Django 2.1.7 on 2019-04-11 12:09

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20190330_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='header',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=0, size=[1920, 540], upload_to='header/', verbose_name='header'),
        ),
        migrations.AlterField(
            model_name='team',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=0, size=[500, 300], upload_to='thumbnail/', verbose_name='ヘッダーthumbnail'),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='user',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=0, size=[500, 300], upload_to='thumbnail/', verbose_name='ヘッダーthumbnail'),
        ),
    ]
