# Generated by Django 2.1.5 on 2019-01-31 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gql', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
    ]
