# Generated by Django 2.1.5 on 2019-02-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gql', '0005_auto_20190202_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='owner',
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Specific tags for this user.', related_name='projects', to='gql.Tag', verbose_name='tags'),
        ),
    ]
