# Generated by Django 2.1.5 on 2019-02-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gql', '0006_auto_20190203_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='header',
            field=models.URLField(blank=True, verbose_name='header'),
        ),
        migrations.AddField(
            model_name='project',
            name='logo',
            field=models.URLField(blank=True, verbose_name='logo'),
        ),
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.URLField(blank=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='project',
            name='content',
            field=models.TextField(blank=True, verbose_name='User content'),
        ),
    ]
