# Generated by Django 2.1.5 on 2019-02-03 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20190203_0021'),
        ('gql', '0007_auto_20190203_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='users.Team', verbose_name='代表サークル'),
        ),
    ]
