# Generated by Django 2.1.5 on 2019-02-03 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gql', '0009_project_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'カテゴリー', 'verbose_name_plural': 'カテゴリー'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'キャンプ', 'verbose_name_plural': 'キャンプ'},
        ),
    ]
