# Generated by Django 2.1.5 on 2019-02-03 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gql', '0014_auto_20190203_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='category',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
