# Generated by Django 2.1.5 on 2019-02-08 16:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gql', '0016_auto_20190204_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(blank=True, max_length=150, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', '英数字だけね')], verbose_name='タグ'),
        ),
    ]
