# Generated by Django 2.1.5 on 2019-02-08 16:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gql', '0017_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(blank=True, max_length=6, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', '英数字だけね')], verbose_name='カラーコード'),
        ),
    ]
