# Generated by Django 2.1.5 on 2019-02-11 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gql', '0019_category_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='color',
        ),
    ]
