# Generated by Django 2.1.7 on 2019-02-14 07:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gql', '0021_auto_20190214_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='end_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='project',
            name='start_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
