# Generated by Django 2.1.7 on 2019-03-24 09:40

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('gql', '0025_auto_20190324_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='test_a',
            field=tinymce.models.HTMLField(blank=True, verbose_name='内容2'),
        ),
    ]
