# Generated by Django 2.1.7 on 2019-03-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gql', '0026_project_test_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='test_a',
        ),
        migrations.AddField(
            model_name='project',
            name='contact',
            field=models.CharField(blank=True, max_length=100, verbose_name='連絡先'),
        ),
    ]
