# Generated by Django 2.1.7 on 2019-03-26 15:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gql', '0028_auto_20190324_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_open',
            field=models.BooleanField(default=True, help_text='オープン・終了', verbose_name='open status'),
        ),
        migrations.AddField(
            model_name='tag',
            name='logo',
            field=models.ImageField(blank=True, upload_to='tag/', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(blank=True, max_length=150, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z+]*$', '大小英数字+だけね')], verbose_name='タグ'),
        ),
    ]
