# Generated by Django 2.1.7 on 2019-03-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gql', '0029_auto_20190327_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='連絡先'),
        ),
        migrations.AlterField(
            model_name='project',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='project',
            name='header',
            field=models.ImageField(blank=True, null=True, upload_to='header/', verbose_name='ヘッダー'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='タイトル'),
        ),
        migrations.AlterField(
            model_name='project',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='開催場所'),
        ),
    ]
