# Generated by Django 2.1.7 on 2019-03-30 07:35

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('gql', '0037_auto_20190330_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=0, size=[600, 300], upload_to='thumbnail/', verbose_name='ヘッダーthumbnail'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='logo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=0, size=[200, 200], upload_to='tag/', verbose_name='logo'),
        ),
    ]
